### ISSUE TITLE
Is anyone know any alternative of ng2-select library?

### ISSUE THREAD

**Issue by ambujkhanna** [valor-software/ng2-select#1007]
Hi,

I am using it in my project and it is not compatible Angular 9 and onwards version. I need to replace it and please do let me know if anyone is aware from any good alternative option. Till now I am thinking for Angular Material chips but that have own issues and complexity.

**Comment by ambujkhanna** [comment]
I found really great alternate library. I have implemented and very happy.
https://github.com/ng-select/ng-select

**Comment by CrismariMain** [comment]
> I found really great alternate library. I have implemented and very happy. https://github.com/ng-select/ng-select

Thanks!
