### ISSUE TITLE
App fails to compile when using rootDir in tsconfig

### ISSUE THREAD

**Issue by jasonroyle** [valor-software/ng2-select#161]
As soon as I import either `Select` or `SELECT_DIRECTIVES` I get the following compile errors

```
error TS6059: File '/node_modules/ng2-select/components/select.ts' is not under 'rootDir' 'src'. 'rootDir' is expected to contain all source files.
error TS6059: File '/node_modules/ng2-select/components/select/select-interfaces.ts' is not under 'rootDir' 'src'. 'rootDir' is expected to contain all source files.
error TS6059: File '/node_modules/ng2-select/components/select/select-item.ts' is not under 'rootDir' 'src'. 'rootDir' is expected to contain all source files.
error TS6059: File '/node_modules/ng2-select/components/select/select-pipes.ts' is not under 'rootDir' 'src'. 'rootDir' is expected to contain all source files.
error TS6059: File '/node_modules/ng2-select/components/select/select.ts' is not under 'rootDir' 'src'. 'rootDir' is expected to contain all source files.
```

Here is my tsconfig

```
{
  "compilerOptions": {
    "rootDir": "src",
    "outDir": "build",
    "target": "ES5",
    "module": "system",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  },
  "exclude": [
    "node_modules",
    "typings/browser.d.ts",
    "typings/browser"
  ]
}
```
- angular2: 2.0.0-beta.15
- ng2-select: 1.0.1-beta.0
- typescript: 1.8.10

**Comment by julianpaulozzi** [comment]
+1

**Comment by jamiehall30** [comment]
+1

**Comment by jasonroyle** [comment]
This seems to be due to `.ts` and `.d.ts` files existing within the same directory and causing the typescript compiler to recompile the module and then getting confused because it is outside of the `rootDir`.

**Comment by jasonroyle** [comment]
I found [this ng2-bootstrap issue](https://github.com/valor-software/ng2-bootstrap/issues/128) that appears to be the same problem.

**Comment by jasonroyle** [comment]
I forked the repo and was about to look in to fixing the issue when I noticed [this commit](https://github.com/valor-software/ng2-select/commit/393674c06417e63a2ff4dcfb3a529aa8df173dd7), which seems like it may be the fix that I was looking for due to the `.npmignore` modifications. However I can't test using `npm install ng2-select` or `npm install valor-software/ng2-select`, is there an npm release coming up?

**Comment by valorkin** [comment]
check out latest version
no .ts files in npm :)

**Comment by jasonroyle** [comment]
I can confirm the latest release fixes the issue, thanks!

**Comment by valorkin** [comment]
awesome!

**Comment by Tallyb** [comment]
As for the original question: package-lock can be disabled using npm config set package-lock false.
