### ISSUE TITLE
make it work with angular ^2.0.0-rc.1

### ISSUE THREAD

**Issue by feedyourmind** [valor-software/ng2-select#182]
I tried to use it but I couldn't make it work after the recent modules restructuring

**Comment by valorkin** [comment]
thanks for helping!
If you want write access to this repo, drop me a note :)

**Comment by feedyourmind** [comment]
yes, thank you,  that would be awesome. 
I have a few improvements I would gladly contribute, like the option to specify a template as the content of the dropdown, the ability for the selected value and the items display to be able to change after creation and possibly allow this to be linked to RxJs observable streams etc...
I planning to add such improvements for some things I'm working on, so I would be happy if others benefit from them as well. :)

**Comment by valorkin** [comment]
Welcome to ng2-team :)

**Comment by valorkin** [comment]
permissions granted
