### ISSUE TITLE
Is it possible to remove bootstrap dependency?

### ISSUE THREAD

**Issue by nawalgupta** [valor-software/ng2-select#231]
Is it possible to remove bootstrap dependency?

**Comment by Cowlephant** [comment]
This is useless to me with bootstrap. Could we get some styling hooks so we can style without this dependency?

**Comment by linusbrolin** [comment]
I've made Bootstrap optional in https://github.com/valor-software/ng2-select/pull/375 by adding inputs for overriding the Bootstrap css classes.

**Comment by nawalgupta** [comment]
Thanks
