### ISSUE TITLE
Sanitizing HTML stripped some content

### ISSUE THREAD

**Issue by AndersonDev** [valor-software/ng2-select#315]
I have a warning (5+ at the time):
`WARNING: sanitizing HTML stripped some content (see http://g.co/ng/security#xss)`

**Comment by adrianfaciu** [comment]
Can you show how to reproduce this ? Or what component is causing these warnings.

**Comment by AndersonDev** [comment]
@adrianfaciu 
I have select:

```
<ng-select [allowClear]="true"
              [items]="roles"
          [active]="roles[1]"
              [disabled]="inProgress"
              (data)="setRole($event)"
              placeholder="Виберіть роль">
</ng-select>
```

And data:

```
roles:Array<any> = [
  {id: 1, text: 'Мама'},
  {id: 2, text: 'Батько'},
  {id: 3, text: 'Сестра'},
  {id: 4, text: 'Брат'},
  {id: 5, text: 'Дідусь'},
  {id: 6, text: 'Бабуся'}
];
```

Error occurs when I open select (20 errors!) and 3 when choose item. Select is in `bsModal` and `form` divs.

**Comment by adrianfaciu** [comment]
This might come from Angular itself, with no easy way to fix. Have a look [here](https://github.com/angular/angular/issues/9392) for more info.

**Comment by AndersonDev** [comment]
@adrianfaciu ok. What about initial value #307 ?
