### ISSUE TITLE
clear selected item

### ISSUE THREAD

**Issue by fbarajas** [valor-software/ng2-select#354]
Hi, 

I want to know how I can clear the selected item when the data is refreshed and that selected item is not in the refresh list.

Is there  a way to clear the selected item if the underlying list changes? 

thank you!

**Comment by fbarajas** [comment]
I found a working solution. I am using "component interaction":

--these go on the top
import {ViewChild } from "@angular/core";
import {SelectComponent } from 'ng2-select/ng2-select';

--these goes in your export class component
--myDivId is used like this 
@ViewChild('myDivId')
private mySelectList: SelectComponent;

then in your function you call it like this:
if (this.mySelectList) {
var activeItem = this.mySelectList.activeOption;
if (activeItem) {
this.mySelectList.remove(activeItem)
}
}

this will remove the selection if youre using ng2-select in single mode. you can modify this to remove multiple items if youre using it in multiple mode.

I hope it helps.

**Comment by closer27** [comment]
Thank you, I've found this 😃

**Comment by closer27** [comment]
In addition, If you want to clear all selections

if (this.dataSourceSelectComponent) {
  let itemObjects = this.dataSourceSelectComponent.itemObjects;
  for (let itemObject of itemObjects) {
    this.dataSourceSelectComponent.remove(itemObject);
  }
}

this may be helpful
