### ISSUE TITLE
cant set active / selected items

### ISSUE THREAD

**Issue by EEimer** [valor-software/ng2-select#382]
Hey, i am using ng2-select and i am quiet satisfied.
I spent the last 3 hours to set the initial data of the select.

My first attempt was to use "active:
code:

```
<ng-select  [active]="active"... 
public active = ['Amsterdam'];
```

Compiler: 

> Can't bind to 'active' since it isn't a known property of 'ng-select'

After that I tried around with some hacks but so far I couldnt find a solution.
I also want to use it as a multi select, but i am already failing on the single selection.
Unfortunately there is no demo and i am out of ideas..

Another little thought: 
CSS height is not working correctly. 
I have to set the height initially but if it changes (like on multiselect), therefore the hight stays the same..

Thank you for this very helpful component! 

Greetings 
Emanuel

**Comment by bradseefeld** [comment]
Dupe of #379? I too have been trying to get `[active]` to work. On #379, he says to use `[initData]`

**Comment by EEimer** [comment]
nope tried that, too.
Same didnt work

**Comment by lacma2011** [comment]
I had this problem, it was actually giving me errors for using "data" to populate the initial selected values in rc5, because there is an event called "data" which causes a conflict. 
So reading the source I did bump into [initData] and it worked.

**Comment by EEimer** [comment]
I think maybe I maybe had some conflicts with the RC versions. With initData it's fine after setup changes. 
The readme on github is not updated yet.

**Comment by rubenkuipers** [comment]
I'm having the same issue here. It looks like the right attribute should be [active] right now in stead of [initData], but I keep getting this error: 
`selectedItems.map is not a function`

**Comment by XidongHuang** [comment]
have the same problem here: 
`[active]="value[0]"` then
`selectedItems.map is not a function`

**Comment by karmis** [comment]
[active]="value[0]" must be the array

**Comment by rubenkuipers** [comment]
@karmis Do you have a working example?

**Comment by elmartino** [comment]
same here.. selectedItems.map is not a function

**Comment by rubenkuipers** [comment]
I have found the solution, you need to set the active attribute like this: 
[active]="[arrayWithObjects[objectIndex]]"

In most cases this means you should refactor your data object to this format to get It working.

**Comment by elmartino** [comment]
Thanks! In my case it was just [active]="[object]", because it was a single object!

**Comment by elmartino** [comment]
@kuiperr005 Are you able to change a value after setting the [active] data binding? I get the error self.context.onAssignedSelected is not a function after changing a value then..

**Comment by elmartino** [comment]
anybody had success with an array of objects as active property? how to do this?

**Comment by XidongHuang** [comment]
```
import { SelectComponent } from '../node_modules/ng2-select/';

export class SelectButtonComponent {

@ViewChild(SelectComponent) select: SelectComponent;

     public method(e:any):void {
          this.select.active = [value.toString()];
     }

}
```
I used the way that directly change its active value in '**SelectComponent**',  hope it works for you.

**Comment by jasonspick** [comment]
I found this when trying to solve in reactive forms. Need to setValue like this:

`this.select.active = [item.category];`
  `this.form.setValue({
                        name:this.item.name,
                        description:this.item.description,
                        category:[this.item.category.name],
                    });`

this is assuming that you are using objects and not strings as items.

**Comment by qingbingyan** [comment]
thanks @XidongHuang

**Comment by FrancescoBorzi** [comment]
just using `[active]="myInitialStringArray"` worked for me

**Comment by RicoSchueppel** [comment]
[items] already contains all items to be displayed .. I just want to select one of those to be selected initially .. how to do that? why i should give the data again via active ?
