### ISSUE TITLE
Error: Unexpected value 'undefined' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by matthewhegarty** [valor-software/ng2-select#440]
I get the following when I try to run the app:

```
Error: Unexpected value 'undefined' imported by the module 'AppModule'
```

I have tried variations of the imports but get errors.  I am fairly new to Angular2 so am guessing a bit.

I would appreciate any guidance.  Any pointers to up-to-date installation documentation would be greatly appreciated.

I have cloned the `single-demo.component.ts` component and reference selector in HTML: `<single-demo></single-demo>`

```
import {SelectModule} from 'ng2-select';
...
imports: [SelectModule],
...
```

package.json:

```
"dependencies": { 
     ...
     "ng2-select": "1.1.0"
}
```

systemjs.config.js:

```
map {
    ...
      "ng2-select":                 'node_modules/ng2-select/bundles/ng2-select.min.js'
}
```

Angular 2.0.0

**Comment by matthewhegarty** [comment]
_Update_

got round this with changes in `systemjs.config.js`:

```
map {
    ...
      'ng2-select':                 'node_modules/ng2-select'
}
...
packages: {
... 
     'ng2-select': { defaultExtension: 'js', main: 'ng2-select.js' }
}
```

**Comment by Choleriker** [comment]
Guys, there is another simple solution for this. I have 2 modules which are somehow deep in the structure using each other. I ran into the same problem with circular dependencies with webpack and angular 2. I simply changed the way of how the one module is declared:

```` typescript
....

@NgModule({
    imports: [
        CommonModule,
        FormsModule,
        require('../navigation/navigation.module')
    ],
    declarations: COMPONENTS,
    exports: COMPONENTS
})
class DppIncludeModule {
    static forRoot(): ModuleWithProviders {
        return {
            ngModule: DppIncludeModule
        };
    }
}

export = DppIncludeModule;
````

When I now using the imports statement on ngModule attribute I simply use:

````typescript

@NgModule({
    imports: [
        CommonModule,
        ServicesModule.forRoot(),
        NouisliderModule,
        FormsModule,
        ChartModule,
        DppAccordeonModule,
        PipesModule,
        require('../../../unbranded/include/include.module')
    ],
....
````

With this all problems are away.
