### ISSUE TITLE
Anyone know how to set this up as module based?

### ISSUE THREAD

**Issue by chambersDon** [valor-software/ng2-select#442]
I had it working with the instruction in [#429](https://github.com/valor-software/ng2-select/issues/429).  Then I upgraded to the latest version and I can't use SELECT_DIRECTIVES (as expected).

I added SelectModule to my imports in the app.module.  I'm not sure what else to do.

Now I get this famliar error:

```
Can't bind to 'initData' since it isn't a known property of 'ng-select'.
1. If 'ng-select' is an Angular component and it has 'initData' input, then verify that it is part of this module.
...
```

That's usually because I don't have the module.

What else do I need to do?

**Comment by erik-ropez** [comment]
It's "active" instead of "initData" now.

**Comment by chambersDon** [comment]
Thanks.  That fixed it.
Now I am at:

> Error in ./SelectComponent class SelectComponent - inline template:106:19 caused by: value.match is not a function

But there are other threads for that.
