### ISSUE TITLE
Repository in NPM and GitHub are not the same

### ISSUE THREAD

**Issue by dicbrus** [valor-software/ng2-select#458]
NPM repository doesn't include *.ts files, only declarations *.d.ts

**Comment by RoopeHakulinen** [comment]
This is a common practice and really important to keep the npm package size as small as possible. You can see the exclusion in the [.npmignore](https://github.com/valor-software/ng2-select/blob/development/.npmignore) of this repository. You never need the actual .ts files, .d.ts contains all the necessary typing information.

**Comment by dicbrus** [comment]
ok, thank you!
