### ISSUE TITLE
angular 2.0.1 cant install dependences.

### ISSUE THREAD

**Issue by armandoramirezdino** [valor-software/ng2-select#467]
Im trying to install ng2-select in angular 2.0.1, but it fails...

Anyone knows what change between versions?

UNMET PEER DEPENDENCY @angular/common@2.0.1
├── UNMET PEER DEPENDENCY @angular/compiler@2.0.1
├── UNMET PEER DEPENDENCY @angular/core@2.0.1
├── UNMET PEER DEPENDENCY @angular/forms@2.0.1
└── ng2-select@1.1.0 

npm WARN ng2-select@1.1.0 requires a peer of @angular/common@2.0.0 but none was installed.
npm WARN ng2-select@1.1.0 requires a peer of @angular/compiler@2.0.0 but none was installed.
npm WARN ng2-select@1.1.0 requires a peer of @angular/core@2.0.0 but none was installed.
npm WARN ng2-select@1.1.0 requires a peer of @angular/forms@2.0.0 but none was installed.

**Comment by BartAllen** [comment]
Same here. Can't update with angular 2.0.1

**Comment by RoopeHakulinen** [comment]
That isn't a failure actually. It just tells that the peer dependency isn't met. You have 2.0.1, but this library explicitly states that 2.0.0 would be required. Everything still works as expected. The possible solution would be to add ^ on the @angular packages in package.json by the library maintainer. For now, just live with the warnings.

**Comment by Scipionh** [comment]
Works fine for me with angular 2.0.1 despite the warning

**Comment by MAW016** [comment]
It depends on version of npm you have. Mine does not allow that. ^ is very easy fix.

**Comment by ssauriera** [comment]
I having same issue with angular 2.2.1.

├── UNMET PEER DEPENDENCY @angular/common@2.2.1
├── UNMET PEER DEPENDENCY @angular/compiler@2.2.1
├── UNMET PEER DEPENDENCY @angular/core@2.2.1
└── UNMET PEER DEPENDENCY @angular/forms@2.2.1

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN ng2-select@1.1.2 requires a peer of @angular/common@2.0.0 but none was installed.
npm WARN ng2-select@1.1.2 requires a peer of @angular/compiler@2.0.0 but none was installed.
npm WARN ng2-select@1.1.2 requires a peer of @angular/core@2.0.0 but none was installed.
npm WARN ng2-select@1.1.2 requires a peer of @angular/forms@2.0.0 but none was installed.

thanks for help.
