### ISSUE TITLE
install from git doesnt work

### ISSUE THREAD

**Issue by grauschnabel** [valor-software/ng2-select#476]
hi there,

When i use 

`"ng2-select": "valor-software/ng2-select#development",`

in my package.json file there are js and ts files missing.  Where does this come from?
Thanks for your ideas,
Martin

**Comment by grauschnabel** [comment]
Ok, i think, it has to do with the build process, so I will figure it out and open a new issue if I think that has to do with the package rather than with my local settings.

**Comment by grauschnabel** [comment]
ok, after installing phantomjs on my system it works.  :)  just to know if someone else has this problem.

**Comment by canibanoglu** [comment]
How exactly does it work? I'm having the same problems, no ts files are pulled from git. JS files are in .gitignore FYI. 

I have phantomjs installed and it still doesn't work and even if it did it would make no sense at all, the files are not pulled from the repository at all. Are you sure you didn't do something else?
