### ISSUE TITLE
Not working with Angular2 CLI

### ISSUE THREAD

**Issue by tigrenok00** [valor-software/ng2-select#493]
Hi,
Could you please help me make this work. I've set up a component just like in the npm example, however, the select is always shown in disabled state and won't open (the "disabled" property is false). No errors in console.
Thanks!

**Comment by LUKEEEEEEE** [comment]
Try with [disabled]='false'

**Comment by tigrenok00** [comment]
As I mentioned, is has disable=false already. I think that it is not really disabled, just grey and not opening (only showing the placeholder). When I set it specifically to disabled=true, it adds the disabled icon on hover, so there is a difference

**Comment by asko1205** [comment]
@tigrenok00 how did you resolve your issue? I'm having a problem similar to what you described.

**Comment by tigrenok00** [comment]
After struggling with more issues (with multiple select, for one), I pretty soon switched to using select2 directly. I honestly cannot remember if the disabled issue worked out or not, sorry...

**Comment by asko1205** [comment]
No problem @tigrenok00, thanks for getting back to me. I ended up resolving my issue! Just in case it helps someone else, I needed to have the following *ngIf to make sure the data was back when the dropdown initialized:
`<ng-select [items]="myItems"
              (selected)="selectNewItem($event)"
              placeholder="Select items"
              *ngIf="myItems.length > 0"></ng-select>`
