### ISSUE TITLE
click event outside should close the select options float panel

### ISSUE THREAD

**Issue by denghuiquan** [valor-software/ng2-select#499]
![image](https://cloud.githubusercontent.com/assets/5303970/19801371/89b02d96-9d31-11e6-9f14-1328d396a5be.png)

**Comment by martijnpieters** [comment]
Six days ago, I've created a pull request to fix this issue: #500. However, it's not accepted yet.

**Comment by martijnpieters** [comment]
I think it's fixed with 43b4c1074fb4700e20b24b35f12ba4c1619b152c

**Comment by SergeyKuryatnick** [comment]
Already fixed :)

**Comment by Reddemonfox** [comment]
Hi, I got the same prob but for the time being I have done a quick hack to solve my problem.
Just use
[disabled]="isDisabledTrue"
(focusout)="removeData(item)"

in your element
where ,

removeData() {
const self = this;
self.isDisabledTrue = true;
setTimeout(() => {
self.isDisabledTrue = false;
}, 10);
}

This will handle both outside click situation and multiple ngSelect dropdown issue as well
