### ISSUE TITLE
Make Angular2 beta.0 compatible ng-for, ng-if, ng-class etc...

### ISSUE THREAD

**Issue by otabekgb** [valor-software/ng2-select#5]
Angular2 has switched to camel case from kebab case.

**Comment by valorkin** [comment]
yes, it will be updated to beta-0

**Comment by multichannel-contact-center** [comment]
We have tried to port the code to Angular2 2.0.0-beta.0.  The changes are as follows:
- remove 'angular2/angular2', use 'angular2/common' and 'angular2/core' instead
- add COMMON_DIRECTIVES, Input, Output, remove unnecessary imports
- remove property and event, use @Input and @Output instead
- remove implements which is not necessary
- ng-if/ng-for/ng-class => ngIf/ngFor/ngClass
- [inner-html] => [innerHtml]
- onInit/onDestroy => ngOnInit/ngOnDestroy
- EventEmitter => EventEmitter(any)
- import {Pipe} from 'angular2/core';  in select-pipes.ts

Attached is the changed select.ts file. We change to .txt for uploading.
Many thanks for your efforts.

[select.txt](https://github.com/valor-software/ng2-select/files/71499/select.txt)

**Comment by valorkin** [comment]
@multichannel-contact-center it worth to make a PR with this changes
good job!

**Comment by otabekgb** [comment]
Thank you very much. Can you commit the changes and publish to npm, please?

**Comment by phongmh307** [comment]
please commit to npm. Thank you

**Comment by vaer-k** [comment]
Can't this issue be closed? @valorkin

**Comment by valorkin** [comment]
yeap, for sure
