### ISSUE TITLE
Invalid filtering due to using "RegExp.test()"

### ISSUE THREAD

**Issue by kfbishop** [valor-software/ng2-select#56]
After banging my head for most of a day, I've stumbled upon an odd side-effect caused by using "RegExp.text() in `select.ts:filter()` (line ~515).  Seems RegExp keeps a back reference from the last test, which negates the next test!   Changing the code to use  <string>.match() resolves this issue, at the theoretical expense of performance.

This can be verified / tested using the following plunker
[Ng2 test() v match() test](http://plnkr.co/edit/SMxfEp3Eznrxsa2udPCC?p=preview)

References:
- [MDN text()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test) - **test() called multiple times on the same global regular expression instance will advance past the previous match**
- [S/O (final answer)](http://stackoverflow.com/questions/10940137/regex-test-v-s-string-match-to-know-if-a-string-matches-a-regular-expression)

**Comment by kfbishop** [comment]
components/select/select.ts:  Line 517

Was:       .filter(option => query.test(option.text) &&
To be:      .filter(option => option.text.match(query) &&

**Comment by valorkin** [comment]
@kfbishop https://github.com/valor-software/ng2-select/pull/57/commits
there a lot of commits
from which I will not be able to generate changelog
