### ISSUE TITLE
Build problems on Windows due to Typescript error

### ISSUE THREAD

**Issue by sirhcybe** [valor-software/ng2-select#617]
I had a lot of problems getting the build running on my Windows 10 machine. First I was getting an error from the ng build saying;

> "ERROR in Error encountered resolving symbol values statically. Could not resolve ng2-select"

I investigate this and found that the ng-select build was failing when the "ngm build -p src --clean" script ran (Building ng2-select (src) [failed] was the error). The ngm-cli would not show me the error even when I used the --verbose tag so I tracked through its source code to find that the ngm build task just runs a typescript compile internally. So I ran tsc -p src and got the following:

> node_modules/@types/node/index.d.ts(49,13): error TS2451: Cannot redeclare block-scoped variable 'global'.
> scripts/typings.d.ts(11,15): error TS2451: Cannot redeclare block-scoped variable 'global'.

So I went into the scripts/typings.d.ts file and removed line 11:
`declare const global:any;`

After that everything built and ran perfectly. I am no expert but it seems that the @types package has replaced the need for that line in the typings file. Should it be removed?

**Comment by turnerguo** [comment]
+1

> scripts/typings.d.ts(11,15): error TS2451: Cannot redeclare block-scoped variable 'global'.

Just comment that line will be works well, since @types/node already have the 'global' variable declared.

**Comment by sirhcybe** [comment]
Closing this old issue that has a resolution.
