### ISSUE TITLE
Setting Default Value

### ISSUE THREAD

**Issue by sandyydk** [valor-software/ng2-select#681]
Hi

I am not able to set the default value in <ng-select> . Tried using [initData] which I think is no longer supported. Any alternatives?

Thanks.

**Comment by gameot** [comment]
Use [active]. 

> active (?Array<any>) - selection data to set. This should be an object with id and text properties in the case of input type 'Single', or an array of such objects otherwise. This option is mutually exclusive with value.

**Comment by exedor** [comment]
And note that even if you use active, it will still only work when given an array with one element (single) or an array with multiple elements (multiple) regardless of whether the input type is single or not. Those docs are either incorrect or there is a bug.
