### ISSUE TITLE
Asyc data on OnInit Not working. 

### ISSUE THREAD

**Issue by coolsharad** [valor-software/ng2-select#688]
Hi 
  I m facing issue while working on ng-select with Asyc request. I m sending request on ngOninit i m getting correct object which need to pass on html, but somehow i can not see the dropdown. below are component code and html codes as well.Sry for my English

ngOnInit(): void {
  
   this.CategoryService.getCategories().subscribe(categories=>{this.CurrentItems=categories,
       
      
       for(let values in this.CurrentItems)
          {  
            this.items.push({
                        id: this.CurrentItems[values].id,
                        text:this.CurrentItems[values].cat_name 
                    })
          }
     console.log(this.items);
   })

   }
------------------------Html code is here----------------
 <ng-select  [allowClear]="true"
                                    [items]="items"
                                    [disabled]="disabled"
                                    (data)="refreshValue($event)"
                                    (selected)="selected($event)"
                                    (removed)="removed($event)"
                                    placeholder="No Category selected" required name="category_name" ngModel #category_name="ngModel" ></ng-select>

----------End------------------

items are always blank, Can i have to put delays when subscribe it. I m thinking that html is loaded well before server receive item details.

**Comment by NardM** [comment]
add *ngIf
`<ng-select` *ngIf="items"
[allowClear]="true"
[items]="items"
[disabled]="disabled"
(data)="refreshValue($event)"
(selected)="selected($event)"
(removed)="removed($event)"
placeholder="No Category selected" required name="category_name" ngModel #category_name="ngModel" >`
To load the first item, and then already withdrawn(Чтобы сначала элемент подгрузился, а потом уже вывелся)

**Comment by coolsharad** [comment]
@NardM its not working for me

**Comment by coolsharad** [comment]
Hi i got the answer , please follow [link](https://github.com/valor-software/ng2-select/issues/635#issuecomment-281094377) here i get my desire result
