### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by Hesesses** [valor-software/ng2-select#836]
How can I have dynamic placeholder value? 
I would like to get the value from a function or use pipe ( | translate)

**Comment by ALFRED-Guillaume** [comment]
Hi @Hesesses,

I tried the following and it was working :

// Template
<ng-select [placeholder]="placeholder"></ng-select>

// Component code
get placeholder() {
    return 'your placeholder';
}

Hope it helps,
Guillaume.

**Comment by Hesesses** [comment]
works 👍
