### ISSUE TITLE
Is it supported?

### ISSUE THREAD

**Issue by talgautb** [valor-software/ng2-select#895]
looks like it is not support, may be some answers from maintainers?

**Comment by murraybauer** [comment]
This library has more issues than entire frameworks.  Someone may need to fork.

**Comment by perrosen** [comment]
Yeah was looking at the amount of issues and last updates. Not feeling very confident with this solution.

**Comment by optimistex** [comment]
Hi. I am continue to develop in the fork: 
https://github.com/optimistex/ngx-select-ex
There is solved a lot of issues. If are you found a new bug then just make an issue in my fork.
